config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      # Protect against timing attacks:
      # - See https://codahale.com/a-lesson-in-timing-attacks/
      # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
      # - Use & (do not use &&) so that it doesn't short circuit.
      # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["ADMIN_USERNAME"])) &
        ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["ADMIN_PASSWORD"]))
    end if !Rails.env.development?
    mount Sidekiq::Web, at: "/sidekiq"

    get 'stats' => "stats#index"
    get 'leaderboard' => "stats#leaderboard"
  end

  scope :module => 'api' do
    resources :markets, only: [:index, :show, :create] do
      member do
        post :reload
      end
    end

    resources :portfolios, only: [:show] do
      member do
        post :reload
      end
    end

    resources :articles, only: [:index]
    resources :stats, only: [:index]
    resources :whitelist, only: [:show]

    if !Rails.env.production?
      post 'webhooks/faucet' => "webhooks#faucet"
    end

    # workaround due to js-ipfs library CORS error: https://community.infura.io/t/ipfs-cors-error/3149/
    post 'ipfs/add' => "ipfs#add"
  end

  root to: 'api/ping#ping'
end

app/views/shared/_flash.html.erb
<% if flash[:info] %>
  <div class="alert alert-success mt-3" role="alert">
    <%= flash[:info].html_safe %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger mt-3" role="alert">
    <%= flash[:error].html_safe %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container mt-auto">
  <hr>
  <p>&copy; Polkamarkets 2021</p>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Polkamarkets Admin', admin_root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto"></ul>
      <ul class="navbar-nav my-2 my-md-0">
        <li class="nav-item">
          <%= link_to 'Create Market', new_admin_market_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>